# Generated by Django 5.0.6 on 2024-07-03 02:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
        ("user_token", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertoken",
            name="token",
            field=models.CharField(
                auto_created=True,
                default=uuid.UUID("f609e128-79ad-4fbd-b384-9bb5e9c0b631"),
                max_length=36,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tokens",
                to="user.user",
            ),
        ),
    ]
